---
- hosts: privcloud
  gather_facts: False
  sudo: yes

  tasks:
        - name: INSTALL PYTHON2
          raw: sudo apt-get -y install python-simplejson

        - name: INSTALL PACKAGES FROM APT
          apt: pkg={{ item }} state=present update_cache=true
          with_items:
                - git
                - nginx
                - python-pip
                - python-dev
                - upstart


        - name: INSTALL PACKAGES FROM PIP
          pip: name={{ item }}
          with_items:
                - virtualenv

        - name: CLONING REPO
          git: repo=https://github.com/grascj/eliza.git dest=/var/www/html/eliza/ accept_hostkey=true force=yes

        - name: CREATE VIRTUALENV
          command: virtualenv /var/www/html/eliza/eliza/eliza_env creates="/var/www/html/eliza/eliza/eliza_env"

        - name: INSTALL VIRTUALENV REQUIREMENTS
          pip:
                name: 
                  - uwsgi 
                  - flask 
                virtualenv: /var/www/html/eliza/eliza/eliza_env


        - name: MOVING STARTUP SCRIPT
          command: mv /var/www/html/eliza/ansible/eliza.conf /etc/init/eliza.conf

        - name: MOVING CONF FILE
          command: mv /var/www/html/eliza/ansible/nginx.conf /etc/nginx/nginx.conf
          
        - name: STARTING ELIZA
          command: start eliza 
          notify:
                - start nginx

  handlers:
         - name: start nginx
           command: service nginx restart
