---
- hosts: privcloud


  vars:
        app_path: /var/www/html/eliza/


  gather_facts: False


  become: yes


  tasks:
        - name: INSTALL PYTHON2
          raw: sudo apt-get -y install python-simplejson


        - name: INSTALL PACKAGES FROM APT
          apt: pkg={{ item }} state=present update_cache=true
          with_items:
                - git
                - nginx
                - python-pip
                - python-dev
                - upstart
                - mysql-server


        - name: INSTALL PACKAGES FROM PIP
          pip: name={{ item }}
          with_items:
                - virtualenv


        - name: CLONING REPO
          git: repo=https://github.com/grascj/eliza.git dest="{{app_path}}" accept_hostkey=true force=yes


        - name: CREATE VIRTUALENV
          command: virtualenv {{ app_path }}eliza/eliza_env


        - name: INSTALL VIRTUALENV REQUIREMENTS
          pip:
                name: 
                  - uwsgi 
                  - flask 
                  - flask-mysql
                  - flask-recaptcha
                  - flask_mail
                virtualenv: "{{app_path}}eliza/eliza_env"


        - name: MOVING STARTUP SCRIPT
          command: mv {{app_path}}ansible/eliza.conf /etc/init/eliza.conf


        - name: MOVING CONF FILE
          command: mv {{app_path}}ansible/nginx.conf /etc/nginx/nginx.conf


        - name: ATTEMPTING TO START ELIZA
          command: start eliza
          register: started
          failed_when: false
          ignore_errors: true
          no_log: true


        - name: RESTARTING ELIZA
          command: restart eliza
          when: started|failed
          register: started


        - name: START NGINX
          command: service nginx restart
          when: started|succeeded


